### ISSUE TITLE
Build not working: etc/beat.yml missing

### ISSUE THREAD

**Issue by jakommo** [eskibars/lmsensorsbeat#1]
@eskibars thanks for creating this Beat. I was playing around with execbeat to achieve this until I realized there is a dedicated lmsensors beat. :smile: 

Trying to build this following the README instructions, results in the following error:

```
jakommo@es-jre ../src/github.com/eskibars/lmsensorsbeat (git)-[master] % glide update --no-recursive
[WARN] The name listed in the config file (.) does not match the current location (github.com/eskibars/lmsensorsbeat)
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for github.com/elastic/beats.
[INFO] Setting version for github.com/elastic/beats to ae30528774fffa5879392388f651286785118d38.
[WARN] Skipping lockfile generation because full dependency tree is not being calculated
jakommo@es-jre ../src/github.com/eskibars/lmsensorsbeat (git)-[master] % make update
bash ./vendor/github.com/elastic/beats/libbeat/scripts/update.sh lmsensorsbeat github.com/eskibars/lmsensorsbeat ./vendor/github.com/elastic/beats/libbeat
Beat name: lmsensorsbeat
Beat path: ../lmsensorsbeat
Start modifying beat
Update config file
cat: etc/beat.yml: No such file or directory
Update fields
Traceback (most recent call last):
  File "./vendor/github.com/elastic/beats/libbeat/scripts/generate_fields_docs.py", line 118, in <module>
    input = open(beat_path + "/etc/fields.yml", 'r')
IOError: [Errno 2] No such file or directory: '/home/jakommo/go/src/github.com/eskibars/lmsensorsbeat/etc/fields.yml'
make: *** [update] Error 1
```

Cant find `beat.yml` in the repo, should it be `lmsensorsbeat.yml`?

**Comment by eskibars** [comment]
I'll fix it, but unfortunately it's not as trivial as just adding beat.yml.  For now, the workaround is just run `make` instead of `make update` and it should build fine.

**Comment by jakommo** [comment]
Thanks @eskibars, that worked. I've discovered two more things and created https://github.com/eskibars/lmsensorsbeat/pull/2

**Comment by polyfractal** [comment]
So I ran into this as well, but it was with a plain `make`:

```
make
glide update  --no-recursive
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for github.com/eskibars/gosensors.
[INFO] Fetching updates for github.com/elastic/beats.
[INFO] Setting version for github.com/eskibars/gosensors to 9ae18da104c998f3515b03f115dddf29e73bd193.
[INFO] Setting version for github.com/elastic/beats to ae30528774fffa5879392388f651286785118d38.
[WARN] Skipping lockfile generation because full dependency tree is not being calculated
make update
make[1]: Entering directory `/home/polyfractal/projects/elasticsearch/lmsensorsbeat'
bash ./vendor/github.com/elastic/beats/libbeat/scripts/update.sh lmsensorsbeat github.com/eskibars/lmsensorsbeat ./vendor/github.com/elastic/beats/libbeat
Beat name: lmsensorsbeat
Beat path: ../lmsensorsbeat
Start modifying beat
Update config file
cat: etc/beat.yml: No such file or directory
Update fields
Traceback (most recent call last):
  File "./vendor/github.com/elastic/beats/libbeat/scripts/generate_fields_docs.py", line 1, in <module>
    import yaml
ImportError: No module named yaml
make[1]: *** [update] Error 1
make[1]: Leaving directory `/home/polyfractal/projects/elasticsearch/lmsensorsbeat'
make: *** [init] Error 2
```

Subsequent invocations of `make` give:

```
 make
go build
main.go:6:2: cannot find package "github.com/elastic/beats/libbeat/beat" in any of:
    /usr/lib/go/src/pkg/github.com/elastic/beats/libbeat/beat (from $GOROOT)
    /home/polyfractal/.go/src/github.com/elastic/beats/libbeat/beat (from $GOPATH)
main.go:8:2: cannot find package "github.com/eskibars/lmsensorsbeat/beater" in any of:
    /usr/lib/go/src/pkg/github.com/eskibars/lmsensorsbeat/beater (from $GOROOT)
    /home/polyfractal/.go/src/github.com/eskibars/lmsensorsbeat/beater (from $GOPATH)
make: *** [build] Error 1
```

All that said, I know essentially zero golang or the ecosystem, so i may have done something horribly, horribly wrong :)

**Comment by jakommo** [comment]
@polyfractal what is your `$GOROOT` and `$GOPATH`  and where does the `lmsensorsbeat` dir reside? 
Struggled with this problem as well (on every go project I try to build) :smile: 
How does the `vendor/` dir within the `lmsensorsbeat` dir look like? 
I have:

```
vendor/github.com/elastic/beats
vendor/github.com/eskibars/gosensors
```

and from the output you posted it looks like these were pulled in for you as well:

```
[INFO] Downloading dependencies. Please wait...
[INFO] Fetching updates for github.com/eskibars/gosensors.
[INFO] Fetching updates for github.com/elastic/beats.
```

So it might just be a wrong `$GOROOT` or `$GOPATH` setting.

**Comment by polyfractal** [comment]
Brand new OS and installation, so I just created a .go directory under my home and set that as the gopath.  Should goroot be set to something too?

```
echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/polyfractal/bin/gradle-2.12/bin:/home/polyfractal/.go/bin
➜  lmsensorsbeat git:(master) ✗ echo $GOPATH
/home/polyfractal/.go
➜  lmsensorsbeat git:(master) ✗ echo $GOROOT

```

Vendor directory looks good (I think, based on what you said):

```
➜  lmsensorsbeat git:(master) ✗ tree -d -L 4
.
├── beater
├── config
├── tests
│   └── system
│       └── config
└── vendor
    └── github.com
        ├── elastic
        │   └── beats
        └── eskibars
            └── gosensors
```

Edit: Hmm, goroot is set here:

```
lmsensorsbeat git:(master) ✗ go env
GOARCH="amd64"
GOBIN=""
GOCHAR="6"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/polyfractal/.go"
GORACE=""
GOROOT="/usr/lib/go"
GOTOOLDIR="/usr/lib/go/pkg/tool/linux_amd64"
TERM="dumb"
CC="gcc"
GOGCCFLAGS="-g -O2 -fPIC -m64 -pthread"
CXX="g++"
CGO_ENABLED="1"
```

**Comment by jakommo** [comment]
The layout looks correct according to this [doc](https://github.com/golang/go/wiki/GOPATH#introduction).

For me GOPATH and GOROOT both point to `~/go` but I did install it manually to `~/go`, so not sure how that would behave on a package installation. 

What looks strange is that the error is indicating it couldn't find the dir in `/home/polyfractal/.go/src/github.com/elastic/beats/libbeat/beat` but the path looks correct. 
Does the dir exist and contain the beats data?

**Comment by polyfractal** [comment]
Yeah, so the path is correct, and the directory exists (I created them just to be sure), but the directory is empty.  E.g. there isn't anything in `.go/src`.

Do I need to place the lmsensorbeats directory inside the gopath directory?  I thought that was just where dependencies were downloaded?

**Comment by jakommo** [comment]
Ah, that might do it.
Mine looks like this:

```
% tree  -d -L 2 ~/go/src/github.com
/home/jakommo/go/src/github.com
├── christiangalsterer
│   └── execbeat -> /home/jakommo/workspace/ELASTIC/execbeat
├── elastic
│   └── beats
├── eskibars
│   └── lmsensorsbeat
├── golang
│   └── example
├── Masterminds
│   └── glide
└── pierrre
    └── gotestcover

```

**Comment by eskibars** [comment]
This should all be fixed via https://github.com/eskibars/lmsensorsbeat/pull/6 .  I tested locally, but @polyfractal or @jakommo can you try & confirm?

**Comment by jakommo** [comment]
@eskibars tried it on a clean setup and `make` works fine now.
`make update` still fails though:

```
 % make update
bash ./vendor/github.com/elastic/beats/libbeat/scripts/update.sh lmsensorsbeat github.com/eskibars/lmsensorsbeat ./vendor/github.com/elastic/beats/libbeat
Beat name: lmsensorsbeat
Beat path: ../lmsensorsbeat
Start modifying beat
Update config file
Update fields
Traceback (most recent call last):
  File "./vendor/github.com/elastic/beats/libbeat/scripts/generate_fields_docs.py", line 119, in <module>
    output = open(beat_path + "/docs/fields.asciidoc", 'w')
IOError: [Errno 2] No such file or directory: '/home/jakommo/go/src/github.com/eskibars/lmsensorsbeat/docs/fields.asciidoc'
vendor/github.com/elastic/beats/libbeat/scripts/Makefile:206: recipe for target 'update' failed
make: *** [update] Error 1
```

**Comment by eskibars** [comment]
Fixed via https://github.com/eskibars/lmsensorsbeat/pull/7
